demo1:
    path: /
    controller: App\Controller\HelloController::demo1

# put demo3 before demo2 for priority
demo3:
    path: /hello/{id}
    requirements: { id: \d+ }
    controller: App\Controller\HelloController::demo3

demo2:
    path: /hello/{name}
    controller: App\Controller\HelloController::demo2
